FROM apache/superset:6.0.0

USER root

RUN /app/.venv/bin/python -m ensurepip \
 && /app/.venv/bin/python -m pip install --upgrade pip setuptools wheel \
 && /app/.venv/bin/python -m pip install psycopg2-binary

USER superset
