FROM python:3.12-slim

RUN apt-get update && apt-get install -y git curl && \
    pip install --no-cache-dir dbt-core==1.11.2 dbt-postgres==1.10.0

WORKDIR /dbt

COPY dbt/ /dbt/

ENV DBT_PROFILES_DIR=/dbt/.dbt

RUN dbt deps

CMD ["tail", "-f", "/dev/null"]
